[[runners]]
  name = "docker"
  url = "https://gitlab.com/"
  token = "glpat-VRjtKUzBdnHdEds2Ccjx"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "maven:3.8.4-openjdk-17-slim"
    privileged = true
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    disable_entrypoint_overwrite = false
    volumes = ["/cache"]
